.TH LINUX_LOGO 1 "26 March 1999" "Debian" "Debian GNU/Linux Manual"
.SH NAME
linux_logo \- Color ANSI penguin logo w/ system information.
.SH SYNOPSIS
.BR "linux_logo " [ "-h" " | " "-v" " ] [" "-a" " ] [ " "-b" " | " "-c" "] [" "-d" " ] [" "-f" "] [" "-g" " | " "-l" "] [" "-n" "] [" "-p" "] [" "-s" "] [" "-u" "] [" "-x" "] [" "-y" "] [" "-kX" "] [" "-o Num" "] [" "-rX" "] [" "-t string" "] [" "-w Num" "]"
.SH "DESCRIPTION"
.B linux_logo
.SM
is a program that generates a color ANSI picture of a penguin which
includes some system information obtained from the /proc filesystem.
.SH OPTIONS
.TP
.B \-h
Show summary of options.
.TP
.B \-v
Show version of program.
.TP
.B \-ascii -a
Display the logo as monochrome ascii.
.TP
.B \-banner -b
Display the banner-style logo.
.TP
.B \-classic -c
Display the original penguin logo.
.TP
.B \-d
Disable "prettying" of output.
.TP
.B \-f
Force the screen clear before drawing the logo.
.TP
.B \-g
Display only the system infomation.
.TP
.B \-l
Display only the logo.
.TP
.B \-n
Do not display the 'Classic' logo background periods.
.TP
.B \-s
Skip the BogoMips test [ speeds up display on non-Linux platforms ].
.TP
.B \-t string
Display an arbitrary string
.TP
.B \-u
Display the system uptime.
.TP
.B \-x
Display Narrow Logo.
.TP
.B \-y
Display the load average.
.TP
.B \-kX
Replace the background character with X.
.TP
.B \-o Num
Offset the output by Num spaces to the right.
.TP
.B \-p
Preserve the cursor location.
.TP
.B \-rX
Replace the '#' character, in banner mode, with X.
.TP
.B \-w Num
Set the screen width to Num [ default is 80 ].
.TP
.B \-F String
Use "String" to Format the output of the system information.
See the README file for more details.

Quick Reference
____________________________________
  ##     #
  #B     Bogomips                       
  #C     Compiled Date                
  #E     User Text [given with the -t]       
  #H     Hostname                          
  #L     Load average                       
  #M     Megahertz [where supported]        
  #N     Number of CPU's                     
  #O     Operating System Name               
  #R     Ram [in Megabytes]                 
  #S     Plural                            
  #T     Type of CPU                         
  #U     Uptime                              
  #V     Version of OS                     
  #X     CPU Vendor                          
  \\n     carriage return
.SH DEBIAN
The Debian pre-packaged version of
.B linux_logo
is compiled with the 'Classic' logo as the default logo. And the 'Classic' logo has been modified to display 'Debian' instead of 'Linux'.
.PP
The Debian linuxlogo package includes a utility,
.BR linuxlogoconfig (8)
for selecting if the linuxlogo is displayed at boot time or at the login prompt.
.SH "SEE ALSO"
.IR /usr/doc/linux_logo ", http://www.glue.umd.edu/~weave"
.SH AUTHOR
.TP
Vince Weaver
<weave@eng.umd.edu>.
.PP
This manual page was written by Steve Kostecke <steve@debian.org>,
for the Debian GNU/Linux system.

