const char *ascii_logo[]={
"           .........             DDDD   EEEEEE BBBB   IIIIII  AAAA   NN   NN",
"        ...............          DD DD  EE     BB BB    II   AA  AA  NNN  NN",
"      .....          ....        DD  DD EEEEE  BBBBB    II   AAAAAA  NNNN NN",
"     .....    .....    ....      DD  DD EE     BB  BB   II   AA  AA  NN NNNN",
"   .....    .........   ....     DDDD   EEEEEE BBBBB  IIIIII AA  AA  NN   NN",
"  .....    ....   ....  ....   ",
" .....    ....     ...  ....   ",
" .....     ....  ...   ....    ",
"  .....     ....      ....     ",
"   .....     ....  .....       ",
"    .....      .......         ",
"     .....                     ",
"      .....                    ",
"        .....                  ",
"          ......               ",
"             .......           ",
};
