CC = gcc
CFLAGS = -Wall -O2
CPPFLAGS = -I..
LFLAGS =


OS = $(shell uname)

ARCH = $(shell uname -m)

LIBSYSINFO = libsysinfo-0.2.0

PREFIX = /usr/local/


INSTALL= /usr/bin/install -c

INSTALL_BINPATH    = $(PREFIX)/bin
INSTALL_MANPATH    = $(PREFIX)/share/man
INSTALL_DOCPATH    = $(PREFIX)/share/doc
INSTALL_LOCALEPATH = $(PREFIX)/share/locale
PACKAGE = linux_logo
